import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize
from matplotlib.colorbar import ColorbarBase
from bezier_aproximation import bezier_curve

def asinh_scale(x):
    return np.arcsinh(x / 2) / np.log(10)

def sinh_scale(x):
    return 2 * np.sinh(np.log(10) * x)

def generate_initial_matrix_with_bezier_curve():
    """
    Generate the initial matrix and plot a heatmap using a Bezier curve.
    """
    p = 0.5
    y = bezier_curve(50, p)

    # Create a 50x5 empty matrix
    matrix = np.empty((5, 50))

    # Fill every column with the y values generated by the Bezier curve.
    for i in range(5):
        matrix[i, :] = y

    return matrix
